### ISSUE TITLE
Add ability to export topology.json from cluster

### ISSUE THREAD

**Issue by ttindell2** [heketi/heketi#871] opened 2017-09-28 16:25 UTC
It would be very nice if you could do:

heketi-cli topology export --file topology.json

This would be nice in case you want to easily add more devices to your cluster and you have missplaced your original topology file, or if your topology file was created in an automated script and not persisted.

**Comment by raghavendra-talur** [comment] 2017-10-12 05:58
@ttindell2 this is already being tracked with #753 and I have a PR on #754 . I will close this as a duplicate. Would like your review on the original issue.

Duplicate of #753

**Comment by obnoxxx** [comment] 2017-11-03 07:55
closing as duplicate. please follow up on #753

**Closed by obnoxxx** 2017-11-03 07:55 UTC
