### ISSUE TITLE
Heketi-cli: Error handling 

### ISSUE THREAD

**Issue by NehaRawat** [heketi/heketi#327] opened 2016-05-13 15:57 UTC
Currently Heketi-cli doesn't provide proper error messages for most of the options

For example

heketi-cli volume create --name=testvol --size=10 --durability="replicate"  --replica=2
Error: Process exited with: 1. Reason was:  ()

Heketi-logs:

Err[Process exited with: 1. Reason was:  ()]: Stdout []: Stderr [volume create: testvol: failed: Volume testvol already exists
]

**Comment by lpabon** [comment] 2016-05-13 16:49
Yeah I agree, they are terrible messages :smile: .

Duplicate of #171

**Comment by lpabon** [comment] 2016-06-02 03:40
Closed by #366

**Closed by lpabon** 2016-06-02 03:40 UTC
