### ISSUE TITLE
The Docker Image on Docker Hub is 1 year old

### ISSUE THREAD

**Issue by GarethOates** [heketi/heketi#1454] opened 2018-12-10 20:48 UTC
### Kind of issue
Docker image is out of date compared to source

> Uncomment only one of these:
> 
 Bug
> Feature request

### Observed behavior
According to Docker hub the heketi/heketi-rpi image is over 1 year old.

### Expected/desired behavior
The latest image would be uploaded from the latest change to the Dockerfile 24 days ago.

### Details on how to reproduce (minimal and precise)
N/A

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by phlogistonjohn** [comment] 2019-03-29 14:09
Considering a duplicate of https://github.com/heketi/heketi/issues/1470
This issue is technically older but there's more discussion on that issue.

**Closed by phlogistonjohn** 2019-03-29 14:09 UTC
