### ISSUE TITLE
Status error Heketi on CentOS 8 

### ISSUE THREAD

**Issue by Juangunner4** [heketi/heketi#1705] opened 2020-03-28 20:37 UTC
### Kind of issue
> Bug

### Observed behavior

heketi.service - Heketi Server
   Loaded: loaded (/etc/systemd/system/heketi.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Sat 2020-03-28 16:26:24 EDT; 4min 33s ago
  Process: 16642 ExecStart=/usr/local/bin/heketi --config=/etc/heketi/heketi.json (code=exited, status=1/FAILURE)
 Main PID: 16642 (code=exited, status=1/FAILURE)

Mar 28 16:26:24 node3.engr systemd[1]: heketi.service: Service RestartSec=100ms expired, scheduling restart.
Mar 28 16:26:24 node3.engr systemd[1]: heketi.service: Scheduled restart job, restart counter is at 5.
Mar 28 16:26:24 node3.engr systemd[1]: Stopped Heketi Server.
Mar 28 16:26:24 node3.engr systemd[1]: heketi.service: Start request repeated too quickly.
Mar 28 16:26:24 node3.engr systemd[1]: heketi.service: Failed with result 'exit-code'.
Mar 28 16:26:24 node3.engr systemd[1]: Failed to start Heketi Server.

### Expected/desired behavior

Active: active (running)

### Details on how to reproduce (minimal and precise)

reload daemon using: systemctl daemon-reload

heketi.service found below

[Unit]
Description=Heketi Server

[Service]
Type=simple
WorkingDirectory=/var/lib/heketi
EnvironmentFile=-/etc/heketi/heketi.env
User=heketi
ExecStart=/usr/local/bin/heketi --config=/etc/heketi/heketi.json
Restart=on-failure
StandardOutput=syslog
StandardError=syslog

[Install]
WantedBy=multi-user.target

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master):  9.0.0
- Operating system used:  Cent OS 8
- Heketi compiled from sources, as a package (rpm/deb), or container:  rpm
- If container, which container image: none
- Using kubernetes, openshift, or direct install: direct install 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: outside 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom): none 

### Other useful information

I am using port 8080 tcp

**Comment by mhwasil** [comment] 2020-03-29 07:28
Can you check who the owner of `/etc/heketi` is?
If not, change it to `heketi`
```
chown -R heketi:heketi /etc/heketi
```

**Comment by phlogistonjohn** [comment] 2020-03-30 12:43
The logs you provided seem to imply that heketi process itself never started. Since this project does not provide packages for centos I would ensure that that the paths are set up right, and follow the previous suggestion to check ownership and permissions. If that doesn't help, try checking selinux logs and/or run the execstart line by hand to debug it.

**Comment by Juangunner4** [comment] 2020-03-30 22:50
> Can you check who the owner of `/etc/heketi` is?
> `ls -l | grep heketi`
> If that's not `heketi`, change it to `heketi`
> 
> ```
> chown -R heketi:heketi /etc/heketi
> ```

this is the result I get
drwxr-xr-x  2 root root       57 Apr  5  2019 heketi
drwxr-xr-x  4 root root       30 Apr  5  2019 heketi-client
-rw-r--r--  1 root root 10542299 Apr  5  2019 heketi-client-v9.0.0.linux.amd64.tar.gz
-rw-r--r--  1 root root 10542299 Apr  5  2019 heketi-client-v9.0.0.linux.amd64.tar.gz.1
-rw-r--r--  1 root root 23084307 Apr  5  2019 heketi-v9.0.0.linux.amd64.tar.gz
-rw-r--r--  1 root root 23084307 Apr  5  2019 heketi-v9.0.0.linux.amd64.tar.gz.1

but after doing the 
chown -R heketi:heketi /etc/heketi
It still says it is failing with same error as before

**Comment by mhwasil** [comment] 2020-03-31 06:21
> but after doing the
> chown -R heketi:heketi /etc/heketi
> It still says it is failing with same error as before

How does you heketi.json look like?
which user are you using to ssh to the gluster node?
if it's `root` can you ssh to one of the gluster nodes using root user?

**Comment by Juangunner4** [comment] 2020-03-31 21:08
Heketi v9.0.0
ERROR: Unable to parse configuration: json: cannot unmarshal string into Go struct field SshConfig.xfs_sw of type int

**Comment by mhwasil** [comment] 2020-04-01 07:36
> Heketi v9.0.0
> ERROR: Unable to parse configuration: json: cannot unmarshal string into Go struct field SshConfig.xfs_sw of type int

apparently you have a problem with the ssh, can you share the heketi.json file here?
and can you also check `git version` on the heketi server and the gluster nodes and post it here?

**Comment by phlogistonjohn** [comment] 2020-04-01 13:50
> Heketi v9.0.0
> ERROR: Unable to parse configuration: json: cannot unmarshal string into Go struct field SshConfig.xfs_sw of type int

Sounds like the configuration you're providing the server is providing the wrong type for the "xfs_sw" field. This needs to be a numeric value in the JSON, so no quotes. You might even be using some sort of sample/example json. You can't do that and expect it to work out of the box as the examples are not meant to be directly used.

**Comment by Juangunner4** [comment] 2020-04-01 13:52
{
  "_port_comment": "Heketi Server Port Number",
  "port": "8080",

        "_enable_tls_comment": "Enable TLS in Heketi Server",
        "enable_tls": false,

        "_cert_file_comment": "Path to a valid certificate file",
        "cert_file": "",

        "_key_file_comment": "Path to a valid private key file",
        "key_file": "",


  "_use_auth": "Enable JWT authorization. Please enable for deployment",
  "use_auth": false,

  "_jwt": "Private keys for access",
  "jwt": {
    "_admin": "Admin has access to all APIs",
    "admin": {
      "key": "ivd7dfORN7QNeKVO"
    },
    "_user": "User only has access to /volumes endpoint",
    "user": {
      "key": "gZPgdZ8NtBNj6jfp"
    }
  },

  "_backup_db_to_kube_secret": "Backup the heketi database to a Kubernetes secret when running in Kubernetes. Default is off.",
  "backup_db_to_kube_secret": false,

  "_profiling": "Enable go/pprof profiling on the /debug/pprof endpoints.",
  "profiling": false,

  "_glusterfs_comment": "GlusterFS Configuration",
  "glusterfs": {
    "_executor_comment": [
      "Execute plugin. Possible choices: mock, ssh",
      "mock: This setting is used for testing and development.",
      "      It will not send commands to any node.",
      "ssh:  This setting will notify Heketi to ssh to the nodes.",
      "      It will need the values in sshexec to be configured.",
      "kubernetes: Communicate with GlusterFS containers over",
      "            Kubernetes exec api."
    ],
    "executor": "mock",

    "_sshexec_comment": "SSH username and private key file information",
    "sshexec": {
      "keyfile": "/etc/heketi/heketi_key",
      "user": "root",
      "port": "22",
      "fstab": "/etc/fstab",
      "pv_data_alignment": "Optional: Specify PV data alignment size. Default is 256K",
      "vg_physicalextentsize": "Optional: Specify VG physical extent size. Default is 4MB",
      "lv_chunksize": "Optional: Specify LV chunksize. Default is 256K",
      "xfs_sw": "Optional: Specify number of data disks in the underlying RAID device",
      "xfs_su": "Optional: Specifies a stripe unit or RAID chunk size.",
      "backup_lvm_metadata": false,
      "gluster_cli_timeout": "Optional: Timeout, in seconds, passed to the gluster cli invocations",
      "_debug_umount_failures": "Optional: boolean to capture more details in case brick unmounting fails",
      "debug_umount_failures": true
    },

    "_kubeexec_comment": "Kubernetes configuration",
    "kubeexec": {
      "host" :"https://kubernetes.host:8443",
      "cert" : "/path/to/crt.file",
      "insecure": false,
      "user": "kubernetes username",
      "password": "password for kubernetes user",
      "namespace": "OpenShift project or Kubernetes namespace",
      "fstab": "Optional: Specify fstab file on node.  Default is /etc/fstab",
      "pv_data_alignment": "Optional: Specify PV data alignment size. Default is 256K",
      "vg_physicalextentsize": "Optional: Specify VG physical extent size. Default is 4MB",
      "lv_chunksize": "Optional: Specify LV chunksize. Default is 256K",
      "xfs_sw": "Optional: Specify number of data disks in the underlying RAID device.",
      "xfs_su": "Optional: Specifies a stripe unit or RAID chunk size.",
      "backup_lvm_metadata": false,
      "gluster_cli_timeout": "Optional: Timeout, in seconds, passed to the gluster cli invocations",
      "_debug_umount_failures": "Optional: boolean to capture more details in case brick unmounting fails",
      "debug_umount_failures": true
    },

    "_db_comment": "Database file name",
    "db": "/var/lib/heketi/heketi.db",

     "_refresh_time_monitor_gluster_nodes": "Refresh time in seconds to monitor Gluster nodes",
    "refresh_time_monitor_gluster_nodes": 120,

    "_start_time_monitor_gluster_nodes": "Start time in seconds to monitor Gluster nodes when the heketi comes up",
    "start_time_monitor_gluster_nodes": 10,

    "_loglevel_comment": [
      "Set log level. Choices are:",
      "  none, critical, error, warning, info, debug",
      "Default is warning"
    ],
    "loglevel" : "debug",

    "_auto_create_block_hosting_volume": "Creates Block Hosting volumes automatically if not found or exsisting volume exhausted",
    "auto_create_block_hosting_volume": true,

    "_block_hosting_volume_size": "New block hosting volume will be created in size mentioned, This is considered only if auto-create is enabled.",
    "block_hosting_volume_size": 500,

    "_block_hosting_volume_options": "New block hosting volume will be created with the following set of options. Removing the group gluster-block option is NOT recommended. Additional options can be added next to it separated by a comma.",
    "block_hosting_volume_options": "group gluster-block",

    "_pre_request_volume_options": "Volume options that will be applied for all volumes created. Can be overridden by volume options in volume create request.",
    "pre_request_volume_options": "",

    "_post_request_volume_options": "Volume options that will be applied for all volumes created. To be used to override volume options in volume create request.",
    "post_request_volume_options": ""
  }
}

**Comment by Juangunner4** [comment] 2020-04-01 13:55
I do not have git installed I used wget and rpm I used this guide here. https://computingforgeeks.com/setup-glusterfs-storage-with-heketi-on-centos-server/

**Comment by mhwasil** [comment] 2020-04-01 13:57
> I do not have git installed I used wget and rpm I used this guide here. https://computingforgeeks.com/setup-glusterfs-storage-with-heketi-on-centos-server/

sorry, I mean `ssh version`, just edited my comment

**Comment by Juangunner4** [comment] 2020-04-01 14:04
ssh version OpenSSH_7.8p1, OpenSSL 1.1.1 FIPS  11 Sep 2018
Yes I am able to ssh to the nodes just fine using password less ssh.
`ssh -i /etc/heketi/heketi_key root@node14.engr`

**Comment by mhwasil** [comment] 2020-04-01 14:08
> 
> Sounds like the configuration you're providing the server is providing the wrong type for the "xfs_sw" field. This needs to be a numeric value in the JSON, so no quotes. You might even be using some sort of sample/example json. You can't do that and expect it to work out of the box as the examples are not meant to be directly used.

maybe you could try this, remove the stuff that you dont really need, like the this:
```
"_sshexec_comment": "SSH username and private key file information",
"sshexec": {
  "keyfile": "/etc/heketi/heketi_key",
  "user": "root",
  "port": "22",
  "fstab": "/etc/fstab",
  "debug_umount_failures": true
},

```

**Comment by Juangunner4** [comment] 2020-04-01 14:14
> > Sounds like the configuration you're providing the server is providing the wrong type for the "xfs_sw" field. This needs to be a numeric value in the JSON, so no quotes. You might even be using some sort of sample/example json. You can't do that and expect it to work out of the box as the examples are not meant to be directly used.
> 
> maybe you could try this, remove the stuff that you dont really need, like the this:
> 
> ```
> "_sshexec_comment": "SSH username and private key file information",
> "sshexec": {
>   "keyfile": "/etc/heketi/heketi_key",
>   "user": "root",
>   "port": "22",
>   "fstab": "/etc/fstab",
>   "debug_umount_failures": true
> },
> ```

Would I need to reload anything after the configuration the the JSON file?

**Comment by mhwasil** [comment] 2020-04-01 14:15
> > > Sounds like the configuration you're providing the server is providing the wrong type for the "xfs_sw" field. This needs to be a numeric value in the JSON, so no quotes. You might even be using some sort of sample/example json. You can't do that and expect it to work out of the box as the examples are not meant to be directly used.
> > 
> > 
> > maybe you could try this, remove the stuff that you dont really need, like the this:
> > ```
> > "_sshexec_comment": "SSH username and private key file information",
> > "sshexec": {
> >   "keyfile": "/etc/heketi/heketi_key",
> >   "user": "root",
> >   "port": "22",
> >   "fstab": "/etc/fstab",
> >   "debug_umount_failures": true
> > },
> > ```
> 
> Would I need to reload anything after the configuration the the JSON file?

you can try this first
```
/usr/local/bin/heketi --config=/etc/heketi/heketi.json
```

**Comment by Juangunner4** [comment] 2020-04-01 14:20
[heketi] INFO 2020/04/01 10:18:26 Loaded mock executor
[heketi] INFO 2020/04/01 10:18:26 Volumes per cluster limit is set to default value of 1000
[heketi] INFO 2020/04/01 10:18:26 Block: Auto Create Block Hosting Volume set to true
[heketi] INFO 2020/04/01 10:18:26 Block: New Block Hosting Volume size 500 GB
[heketi] INFO 2020/04/01 10:18:26 Block: New Block Hosting Volume Options: group gluster-block
[heketi] INFO 2020/04/01 10:18:26 GlusterFS Application Loaded
[heketi] INFO 2020/04/01 10:18:26 Started Node Health Cache Monitor
[heketi] INFO 2020/04/01 10:18:26 Started background pending operations cleaner
Listening on port 8080
[heketi] INFO 2020/04/01 10:18:36 Starting Node Health Status refresh
[heketi] INFO 2020/04/01 10:18:36 Cleaned 0 nodes from health cache
^CShutting down...
[heketi] INFO 2020/04/01 10:18:58 Closed

this is the output I get, but it still says it has failed when I do systemctl status heketi

**Comment by mhwasil** [comment] 2020-04-01 14:21
> [heketi] INFO 2020/04/01 10:18:26 Loaded mock executor
> [heketi] INFO 2020/04/01 10:18:26 Volumes per cluster limit is set to default value of 1000
> [heketi] INFO 2020/04/01 10:18:26 Block: Auto Create Block Hosting Volume set to true
> [heketi] INFO 2020/04/01 10:18:26 Block: New Block Hosting Volume size 500 GB
> [heketi] INFO 2020/04/01 10:18:26 Block: New Block Hosting Volume Options: group gluster-block
> [heketi] INFO 2020/04/01 10:18:26 GlusterFS Application Loaded
> [heketi] INFO 2020/04/01 10:18:26 Started Node Health Cache Monitor
> [heketi] INFO 2020/04/01 10:18:26 Started background pending operations cleaner
> Listening on port 8080
> [heketi] INFO 2020/04/01 10:18:36 Starting Node Health Status refresh
> [heketi] INFO 2020/04/01 10:18:36 Cleaned 0 nodes from health cache
> ^CShutting down...
> [heketi] INFO 2020/04/01 10:18:58 Closed
> 
> this is the output I get, but it still says it has failed when I do systemctl status heketi

looks good.
You need to restart your service:
```
sudo systemctl restart heketi
```

**Comment by Juangunner4** [comment] 2020-04-01 14:24
Still says it has failed on the status

**Comment by mhwasil** [comment] 2020-04-01 14:25
can you provide the log?

**Comment by Juangunner4** [comment] 2020-04-01 14:27
Where are the logs stored?

**Comment by mhwasil** [comment] 2020-04-01 14:29
you can do
```
journalctl -xe
```
or copy the output of 
```
sudo systemctl status heketi
```

**Comment by Juangunner4** [comment] 2020-04-01 14:30
> you can do
> 
> ```
> journalctl -xe
> ```
> 
> or copy the output of
> 
> ```
> sudo systemctl status heketi
> ```

 heketi.service - Heketi Server
   Loaded: loaded (/etc/systemd/system/heketi.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Wed 2020-04-01 10:24:12 EDT; 6min ago
  Process: 14615 ExecStart=/usr/local/bin/heketi --config=/etc/heketi/heketi.json (code=exited, status=1/FAILURE)
 Main PID: 14615 (code=exited, status=1/FAILURE)

Apr 01 10:24:12 node3.engr systemd[1]: heketi.service: Service RestartSec=100ms expired, scheduling restart.
Apr 01 10:24:12 node3.engr systemd[1]: heketi.service: Scheduled restart job, restart counter is at 5.
Apr 01 10:24:12 node3.engr systemd[1]: Stopped Heketi Server.
Apr 01 10:24:12 node3.engr systemd[1]: heketi.service: Start request repeated too quickly.
Apr 01 10:24:12 node3.engr systemd[1]: heketi.service: Failed with result 'exit-code'.
Apr 01 10:24:12 node3.engr systemd[1]: Failed to start Heketi Server.

**Comment by phlogistonjohn** [comment] 2020-04-01 14:58
I am not sure where in the world the content of your /etc/heketi/heketi.json came from (the rpm?), but it is not correct for a real production system. You can not use the sample json because it not valid. Its unfortunate that more and more additions to the example json are invalid for a real configuration, and someone could contribute a clean up for that.
That all being said you need to take a step back and properly configure your heketi instance. Start with a minimal configuration that uses one of the valid executors "ssh" or "kube" but not "mock".
Lastly, make sure your systemd unit file matches the ownership of the dirs that heketi needs access to: specifically make sure that user can read the config json and both read and write the heketi db directory.

**Comment by phlogistonjohn** [comment] 2020-04-01 15:05
I just skimmed that link you provided and it has a number of flaws, the worst of which is that it does not ensure data continuity of the heketi db. With heketi installed on one node and the db on local storage if you lose that node you lose all heketi state.
That is ok for a toy setup where you're just messing around with heketi/gluster but I strongly recommend not directly following that approach for a production system.

**Comment by Juangunner4** [comment] 2020-04-01 15:16
> I just skimmed that link you provided and it has a number of flaws, the worst of which is that it does not ensure data continuity of the heketi db. With heketi installed on one node and the db on local storage if you lose that node you lose all heketi state.
> That is ok for a toy setup where you're just messing around with heketi/gluster but I strongly recommend not directly following that approach for a production system.

Thanks, I am new to heketi any idea where I can get more information on how to configure my setup to best fit my needs? I am building a cluster for a University project and would like to use heketi and gluster for volume managing.

**Comment by mhwasil** [comment] 2020-04-01 15:18
> > I just skimmed that link you provided and it has a number of flaws, the worst of which is that it does not ensure data continuity of the heketi db. With heketi installed on one node and the db on local storage if you lose that node you lose all heketi state.
> > That is ok for a toy setup where you're just messing around with heketi/gluster but I strongly recommend not directly following that approach for a production system.
> 
> Thanks, I am new to heketi any idea where I can get more information on how to configure my setup to best fit my needs? I am building a cluster for a University project and would like to use heketi and gluster for volume managing.

I used this one, it worked.

**Comment by mhwasil** [comment] 2020-04-01 15:26
> I just skimmed that link you provided and it has a number of flaws, the worst of which is that it does not ensure data continuity of the heketi db. With heketi installed on one node and the db on local storage if you lose that node you lose all heketi state.
> That is ok for a toy setup where you're just messing around with heketi/gluster but I strongly recommend not directly following that approach for a production system.

it's mentioned [in here] a bit(https://github.com/heketi/heketi/blob/master/docs/admin/server.md)

**Comment by mhwasil** [comment] 2020-04-01 15:49
> [heketi] INFO 2020/04/01 10:18:26 Loaded mock executor
> [heketi] INFO 2020/04/01 10:18:26 Volumes per cluster limit is set to default value of 1000
> [heketi] INFO 2020/04/01 10:18:26 Block: Auto Create Block Hosting Volume set to true
> [heketi] INFO 2020/04/01 10:18:26 Block: New Block Hosting Volume size 500 GB
> [heketi] INFO 2020/04/01 10:18:26 Block: New Block Hosting Volume Options: group gluster-block
> [heketi] INFO 2020/04/01 10:18:26 GlusterFS Application Loaded
> [heketi] INFO 2020/04/01 10:18:26 Started Node Health Cache Monitor
> [heketi] INFO 2020/04/01 10:18:26 Started background pending operations cleaner
> Listening on port 8080
> [heketi] INFO 2020/04/01 10:18:36 Starting Node Health Status refresh
> [heketi] INFO 2020/04/01 10:18:36 Cleaned 0 nodes from health cache
> ^CShutting down...
> [heketi] INFO 2020/04/01 10:18:58 Closed
> 
> this is the output I get, but it still says it has failed when I do systemctl status heketi

I had the very same problem, here is what I did:
1. Check glusterd service running on each gluster node
  ```
  sudo systemctl status glusterd
  ```
  if it's not running, run it
  ```
  sudo systemctl enable glusterd
sudo systemctl start glusterd
  ```
2. Make sure heketi is the owner of the heketi related directories on the heketi server:
```
chown -R heketi:heketi /var/lib/heketi /etc/heketi
```

Here is my heketi.json file

```
{
  "_port_comment": "Heketi Server Port Number",
  "port": "8080",

  "_use_auth": "Enable JWT authorization. Please enable for deployment",
  "use_auth": true,

  "_jwt": "Private keys for access",
  "jwt": {
    "_admin": "Admin has access to all APIs",
    "admin": {
      "key": "adminpassword"
    },
    "_user": "User only has access to /volumes endpoint",
    "user": {
      "key": "userpassword"
    }
  },

  "_glusterfs_comment": "GlusterFS Configuration",
  "glusterfs": {
    "_executor_comment": [
      "Execute plugin. Possible choices: mock, ssh",
      "mock: This setting is used for testing and development.",
      "      It will not send commands to any node.",
      "ssh:  This setting will notify Heketi to ssh to the nodes.",
      "      It will need the values in sshexec to be configured.",
      "kubernetes: Communicate with GlusterFS containers over",
      "            Kubernetes exec api."
    ],
    "executor": "ssh",

    "_sshexec_comment": "SSH username and private key file information",
    "sshexec": {
      "keyfile": "/etc/heketi/id_rsa",
      "user": "root",
      "port": "22",
      "fstab": "/etc/fstab"
    },

    "_kubeexec_comment": "Kubernetes configuration",
    "kubeexec": {
      "host" :"https://kubernetes.host:8443",
      "cert" : "/path/to/crt.file",
      "insecure": false,
      "user": "kubernetes username",
      "password": "password for kubernetes user",
      "namespace": "OpenShift project or Kubernetes namespace",
      "fstab": "Optional: Specify fstab file on node.  Default is /etc/fstab"
    },

    "_db_comment": "Database file name",
    "db": "/var/lib/heketi/heketi.db",

    "_loglevel_comment": [
      "Set log level. Choices are:",
      "  none, critical, error, warning, info, debug",
      "Default is warning"
    ],
    "loglevel" : "debug"
  }
}

```

and my service file:
```
[Unit]
Description=Heketi Server

[Service]
Type=simple
WorkingDirectory=/var/lib/heketi
User=heketi
ExecStart=/usr/bin/heketi --config /etc/heketi/heketi.json
Restart=on-failure
StandardOutput=syslog
StandardError=syslog

[Install]
WantedBy=multi-user.target

```

hope that helps

**Comment by Juangunner4** [comment] 2020-04-01 19:27
I get this when I run ` /usr/local/bin/heketi --config=/etc/heketi/heketi.json`

[cmdexec] ERROR 2020/04/01 15:27:04 heketi/pkg/remoteexec/ssh/ssh.go:87:ssh.NewSshExecWithKeyFile: Unable to get keyfile: ssh: unhandled key type
[cmdexec] ERROR 2020/04/01 15:27:04 heketi/executors/sshexec/sshexec.go:126:sshexec.NewSshExecutor: Unable to read private key file
[heketi] ERROR 2020/04/01 15:27:04 heketi/apps/glusterfs/app.go:158:glusterfs.(*App).setup: Unable to read private key file
ERROR: Unable to start application: Unable to read private key file

**Comment by mhwasil** [comment] 2020-04-01 19:33
> I get this when I run ` /usr/local/bin/heketi --config=/etc/heketi/heketi.json`
> 
> [cmdexec] ERROR 2020/04/01 15:27:04 heketi/pkg/remoteexec/ssh/ssh.go:87:ssh.NewSshExecWithKeyFile: Unable to get keyfile: ssh: unhandled key type
> [cmdexec] ERROR 2020/04/01 15:27:04 heketi/executors/sshexec/sshexec.go:126:sshexec.NewSshExecutor: Unable to read private key file
> [heketi] ERROR 2020/04/01 15:27:04 heketi/apps/glusterfs/app.go:158:glusterfs.(*App).setup: Unable to read private key file
> ERROR: Unable to start application: Unable to read private key file

As I expected, I had this problem too.
The reason is the OpenSSH version of the client (gluster nodes) is different from the server (heketi).
Try regenerate the key using the following comman:
```
ssh-keygen -m PEM -t rsa -b 4096 -q -f
```
Make sure after generating this, heketi is the owner of the key.
and copy your new id_rsa.pub to the gluster nodes again.

It's related to this #1666

**Comment by Juangunner4** [comment] 2020-04-01 19:42
Thank you so much it is now working! Was it because of the ssh being 7.8?

**Comment by mhwasil** [comment] 2020-04-01 19:45
> Thank you so much it is now working! Was it because of the ssh being 7.8?

Nice. Yes, that's the reason.
Apparently heketi only supports the version of the go lib that it was built with.

**Comment by Juangunner4** [comment] 2020-04-01 19:50
should I [https://computingforgeeks.com/setup-glusterfs-storage-with-heketi-on-centos-server/](This one) to configure my topology or use [https://wiki.myhypervisor.ca/books/linux/page/glusterfs-heketi-ubuntu-1804](this other one). Which would you recommend

**Comment by phlogistonjohn** [comment] 2020-04-01 19:52
> > Thank you so much it is now working! Was it because of the ssh being 7.8?
> 
> Nice. Yes, that's the reason.
> Apparently heketi only supports the version of the go lib that it was built with.

This is correct. Do note that you implied the versions of openssh differ, that may be true but does not apply to heketi as the Go libraries heketi uses for SSH are part of the Go crypto libraries and do not share code with or link to openssh (for both good and ill).

**Comment by Juangunner4** [comment] 2020-04-03 00:30
Ran into an issue when creating my topology for Heketi and Gluster. I ran 
`heketi-cli topology load --user admin --secret adminpassword --json=/etc/heketi/topology.json`  

and received this output, cannot I not add a device that already has data?

Allowing file volumes on cluster.
        Allowing block volumes on cluster.
        Creating node masternode.engr ... Unable to create node: New Node doesn't have glusterd running
        Creating node node1.engr ... Unable to create node: New Node doesn't have glusterd running
        Creating node node2.engr ... Unable to create node: New Node doesn't have glusterd running
        Found node node3.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?):   Device /dev/sda excluded by a filter.
        Found node node4.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node5.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node6.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?):   Device /dev/sda excluded by a filter.
        Found node node7.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node8.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node9.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node10.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node11.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
                Adding device /dev/sdd ... Unable to add device: Setup of device /dev/sdd failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node12.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node13.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node14.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?):   Device /dev/sda excluded by a filter.
        Found node node15.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node16.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
        Found node node17.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [publickey none], no supported methods remain
        Found node node18.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
                Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

**Comment by mhwasil** [comment] 2020-04-03 07:18
> and received this output, cannot I not add a device that already has data?

no, you should wipe the disk first
```
sudo wipefs -a /dev/sda
```

> Creating node node1.engr ... Unable to create node: New Node doesn't have glusterd running

Make sure glusterd service running on all nodes (check my previous comment)

> Found node node4.engr on cluster d982a08c8cb3cf67ca89c8369782ab83
> Adding device /dev/sda ... Unable to add device: Setup of device /dev/sda failed (already initialized or contains data?): ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain

Heketi node should have ssh access to all gluster nodes

**Comment by 5331k** [comment] 2020-05-14 08:48
Hi @Juangunner4 , were you able to resolve the issue ?

**Comment by maxisam** [comment] 2020-06-23 23:12
Have the same issue and glusterd is running according to ` systemctl status glusterd`

**Comment by maxisam** [comment] 2020-06-24 11:34
Figured out. Somehow ssh wasn't working correctly. The error message is misleading. If anyone has this issue, check with system log first.

**Comment by phlogistonjohn** [comment] 2020-07-21 18:27
Hi there. v10.0.0 has been released. Since the last update here is about a month old I'm going to close this. Feel free to reopen if the issues seen here can be reproduced on v10.

**Closed by phlogistonjohn** 2020-07-21 18:27 UTC

**Comment by monaminor** [comment] 2020-12-31 11:58
hi i am getting error as
"heketi.service - Heketi Server
   Loaded: loaded (/etc/systemd/system/heketi.service; enabled; vendor preset: disabled)
   Active: failed (Result: exit-code) since Thu 2020-12-31 11:40:18 UTC; 17min ago
  Process: 7122 ExecStart=/usr/local/bin/heketi --config=/etc/heketi/heketi.json (code=exited, status=1/FAILURE)
 Main PID: 7122 (code=exited, status=1/FAILURE)

Dec 31 11:40:18 heketi systemd[1]: heketi.service: Main process exited, code=exited, status=1/FAILURE
Dec 31 11:40:18 heketi systemd[1]: heketi.service: Failed with result 'exit-code'.
Dec 31 11:40:18 heketi systemd[1]: heketi.service: Service RestartSec=100ms expired, scheduling restart.
Dec 31 11:40:18 heketi systemd[1]: heketi.service: Scheduled restart job, restart counter is at 5.
Dec 31 11:40:18 heketi systemd[1]: Stopped Heketi Server.
Dec 31 11:40:18 heketi systemd[1]: heketi.service: Start request repeated too quickly.
Dec 31 11:40:18 heketi systemd[1]: heketi.service: Failed with result 'exit-code'.
Dec 31 11:40:18 heketi systemd[1]: Failed to start Heketi Server."

please help me in solving this
