### ISSUE TITLE
Vagrant+ansible setup for functional tests VMs is failing to install gluster

### ISSUE THREAD

**Issue by phlogistonjohn** [heketi/heketi#1452] opened 2018-12-08 17:39 UTC
Something in the centos/gluster ecosystem has changed and our scripts for setting up gluster on the functional test VMs is no longer working. An rpm named `centos-release-gluster-legacy-4.0-1.el7.centos.noarch` is the only RPM matching gluster on the system. That package provides only one text file with the following contents:

```
[root@storage0 vagrant]# cat /usr/share/doc/README 
Presence of this README indicates that an unmaintained version of Gluster was
enabled on this system. The centos-release-gluster-legacy package caused the
removal of centos-release-gluster* versions that do not receive updates
anymore.

It is strongly recommended to follow the releases for Gluster deployments and
plan for upgrades accordingly. An announcement is sent to the CentOS Announce
and Gluster Announce mailinglists when a new version becomes available.

More details about the versions and their End-Of-Life dates are on
https://www.gluster.org/community/release-schedule
```

### Kind of issue

 Bug

### Observed behavior

Functional tests all fail. Gluster packages are not installed.

### Expected/desired behavior

Gluster packages are installed and functional tests run.

### Details on how to reproduce (minimal and precise)

Always for about a week or so.

**Comment by phlogistonjohn** [comment] 2018-12-08 17:40
@nixpanic any hints for us? I'll take care of fixing up the scripts if you can point us in the right direction.

**Comment by phlogistonjohn** [comment] 2018-12-09 20:04
Great, I'm trying it out right now. Thanks a ton for the assistance!

**Comment by nixpanic** [comment] 2018-12-10 15:12
From https://lists.gluster.org/pipermail/gluster-devel/2018-December/055724.html:

~~~
The issue has been found. Although still unclear why things were working
with previous versions of the packages.

The cause of the problem seems that YUM does not have a predictable way
of handling/resolving packages that have multiple Provides: for a
certain virtual package. In this case centos-release-gluster is provided
by centos-release-gluster{41,5,-legacy} builds. The -legacy package has
multiple "Provides: centos-release-gluster = $VERSION" entries. YUM does
not like that and returns too early from a certain dependency resolver
function.

Updated packages will become available soon. The builds have been passed
on to the CentOS team for signing and pushing to the mirrors. In order
to have the issue resolved on both CentOS 7 & 6, the following updates
have been provided:

- centos-release-gluster-legacy-4.0-2.el7.centos
- centos-release-gluster-legacy-4.0-2.el6.centos
- centos-release-gluster41-1.0-3.el6.centos

As soon as these packages land in CentOS Extras, all jobs will start to
function correctly again.

Niels
~~~

**Closed** 2018-12-18 06:58 UTC
