### ISSUE TITLE
Need to change the log level

### ISSUE THREAD

**Issue by lpabon** [heketi/heketi#221] opened 2015-10-15 21:25 UTC
Need to change the log level either from a rest interface, or from the the config file.

For simplicity, Release 1 will change the log level from the config file.  Release 2 will change it from both the config and a rest interface

**Comment by phlogistonjohn** [comment] 2018-04-04 20:44
Quasi-duplicate of #223. Plus, this issue has not had any activity in years. Closing.

**Closed by phlogistonjohn** 2018-04-04 20:44 UTC
