### ISSUE TITLE
dev image tag pulling returns error pulling image configuration: unknown blob

### ISSUE THREAD

**Issue by aviorma** [heketi/heketi#1792] opened 2020-10-05 13:56 UTC
### Kind of issue

> Uncomment only one of these:
> 
> Bug
> Feature request

### Observed behavior

ubuntu@node1:~$ sudo docker pull heketi/heketi:dev
dev: Pulling from heketi/heketi
c7def56d621e: Pulling fs layer
4ba09fe3c36a: Pulling fs layer
error pulling image configuration: unknown blob

dev image tag pulling returns error pulling image configuration: unknown blob

### Information about the environment:

- Heketi version used (e.g. v6.0.0 or master): 
- Operating system used: 
- Heketi compiled from sources, as a package (rpm/deb), or container: 
- If container, which container image: 
- Using kubernetes, openshift, or direct install: 
- If kubernetes/openshift, is gluster running inside kubernetes/openshift or outside: 
- If kubernetes/openshift, how was it deployed (gk-deploy, openshift-ansible, other, custom):

**Comment by aviorma** [comment] 2020-10-05 14:00
@phlogistonjohn Please note it is breaking production env

**Comment by phlogistonjohn** [comment] 2020-10-05 14:27
Seems like a docker hub issue to me. The tag looks OK in the administrative web view but the blob URL gives a 404. Since our builds are done automatically *by* dockerhub its not a  matter of a failed manual push.

I suggest contacting docker hub support and let them know about this issue. Thanks.

**Comment by raghavendra-talur** [comment] 2020-10-06 17:41
@phlogistonjohn @aviorma I was able to reproduce the issue. I was able to pull the images with "latest" and "10" tags but not the one with "dev" tag.

I triggered a build in docker hub and now I can pull the "dev" image successfully. It was probably an error somewhere in docker hub.

**Comment by aviorma** [comment] 2020-10-06 18:20
@raghavendra-talur  Thanks!

**Comment by raghavendra-talur** [comment] 2020-10-19 14:13
This is fixed now. Closing.

**Closed by raghavendra-talur** 2020-10-19 14:13 UTC
