### ISSUE TITLE
[Enhancement] A method (or, end-point) to enable obtaining health and diagnostics of a system managed by Heketi

### ISSUE THREAD

**Issue by sankarshanmukhopadhyay** [heketi/heketi#1320] opened 2018-08-16 01:22 UTC
### Kind of issue

Feature request

Enabling a method or, ReSTful end point (/health or, /diagnostics) which allows an external agent to query the said method and obtain the state of health for a storage system managed by Heketi

### Observed behavior

All current releases of Heketi provide a method to interact with a metrics system (eg. Prometheus) but do not have a separate/dedicated method to provide an interpretation of the state of health of the cluster. 

### Expected/desired behavior

A /health or, /diagnostics method that can provide a reasonable degree of detail containing status of aspects of the system which indicate that the managed system is healthy

### Details on how to reproduce (minimal and precise)

NA.

### Information about the environment:

NA.

### Other useful information

The feature request is to consider a top-down layered approach where only the key and critical pieces of information are queried and interpreted prior to being published via this defined end-point. Such pieces of information may include

- status of the heketi container and heketi service
- integrity of the topology vis-a-vis actual available devices
- inventory of devices available (device tree?)
- reporting state of provisioned/managed capacity
- are Gluster services available
- are there any core files which have been generated
- are there split-brain conditions (is this a primary check?)
- are there gfid mismatches (is this a primary check?)

**Comment by sankarshanmukhopadhyay** [comment] 2018-08-16 01:27
There is on-going work in Gluster to define what health checks mean. See - https://github.com/gluster/glusterfs/issues/313

**Comment by sankarshanmukhopadhyay** [comment] 2018-08-21 11:43
https://github.com/gluster/glusterd2/issues/538

**Comment by phlogistonjohn** [comment] 2019-11-12 12:48
Sort-of Duplicate of #1412 .  I don't think glusterd2 is a live project any more either.

**Closed by phlogistonjohn** 2019-11-12 12:48 UTC
Labels: enhancement
