### ISSUE TITLE
How to remove bricks safely?

### ISSUE THREAD

**Issue by blurpy** [heketi/heketi#1852] opened 2021-05-07 08:34 UTC
One of our teams have a really large replicated pvc in gluster for minio, managed by heketi in k8s.
Someone resized it by 10gb, and those 2 10gb bricks are now filled with a billion tiny files that use all the inodes. We have increased available inodes once after a full outage of minio, but there is a limit on how many times we can do that, so we need a permanent fix. I tried remove-brick in gluster (in a test env) without commit, which looked good (all files were moved to other bricks) until I noticed that rebalance stops working. I commited the change, and the bricks were deleted, and things look like they still work, but not sure if that breaks something down the line with heketi, since it still references the deleted bricks.

Any suggestions on the best way to get rid of bricks and avoid issues down the line?
Can heketi function without impact even if the database references deleted bricks?

Appreciate any input here.

**Comment by iamniting** [comment] 2021-05-07 08:50
Instead of gluster you can perform this action via heketi brick evict command. This will replace your brick on the existing node on another device or on another node.

If you do perform the operations via gluster directly then there will be a mismatch b/w gluster and heketi. Which can cause problems at later point of time for example you can get a problem while removing device or while deleting volume etc

**Comment by blurpy** [comment] 2021-05-07 12:04
I'm not on heketi 10, but tried to understand the source code to see what it does during evict, and this looks relevant:

https://github.com/heketi/heketi/blob/69b526776a80a2651d2aa70dc6ee1a3421ba6cf8/apps/glusterfs/volume_entry_allocate.go#L330

Looks like it's allocating a new brick based on the size of the old brick.

If there was a version of this command that let me skip creating the replacement brick, it would probably be ok?

**Comment by phlogistonjohn** [comment] 2021-05-07 13:12
It is correct that the evict brick feature replaces the evicted brick with a new one of the same size.

I may be missing something but I don't see why you could not have extended the volume using heketi.  If the issue is related to scaling lots of small files in gluster, I'm not sure what we could do about that.

If there are already bricks in gluster that don't exist in heketi and vice versa, and you want to resolve these inconsistencies there's no bult-in tooling to help with that. You could take heketi offline, dump the db to json, and then edit the json before loading it back into a heketi db. It's risky if you don't know the db format well - so I consider it an "expert" level option - but it has been done. There are some tools in the extras/tools/ dir in the heketi source tree that can help with that, but they're use at your own risk for sure.

**Comment by blurpy** [comment] 2021-05-07 13:28
We do have lots of space left over in the volume, so we don't need to extend anything.

The issue is that the brick sizes are widely different, due to the resize operation of only 10gb at an earlier point. So we have 2 small bricks of 10gb each, and the rest of the bricks are atleast 300gb each and larger, spanning a volume of many tb.
Gluster has some algorithm that tries to keep all the bricks at the same percentage used, and puts more or less all the small files on the 10gb bricks, and the large files on the larger bricks.

The small bricks use all the inodes just for keeping track of the tiny files, and as soon as 1 brick is out of inodes, the whole volume stops functioning, even if there is lots of free space.

I don't know what to do other than get rid of the small bricks to avoid another outage very soon. Right now inode usage is at 75% on the 10gb bricks and the rest are at 1%. It's increasing about 1% a day on the small bricks.

We don't have any inconsistencies between gluster and heketi at the moment, and so we are open for suggestions. I've looked at the db structure, and it seems risky to mess around with.

**Comment by iamniting** [comment] 2021-05-07 13:48
I guess I understand your question now. You want to delete the small bricks directly from the gluster side to get rid of the problem you are having because of the difference in brick sizes. As far as i know gluster you can do that. There should not be much problems, But before doing that i think you can check with the gluster folks.

Heketi should not create many problems for you, It will be a mismatch b/w the gluster and heketi, which will be gone automatically when you delete that volume. But but but if you delete the device heketi will create a bricks of same size for that volume again and attach them to the volume and you will be at the same problem again. So to get out of that problem you have to edit the heketi db, there is no other option around

Things to keep in mind if you delete the bricks:
you need to delete the fstab entries for heketi so that your system won't try to mount those deleted bricks again.

**Comment by blurpy** [comment] 2021-05-07 14:08
> Thanks, that clarifies things a bit. But the number two confuses me. Are you using replica 2? 

That's correct.

> Perhaps I'm barking up the wrong tree but this behavior sounds like something that would need to be resolved by gluster. You might try reaching out to the gluster team in their mailing list if you haven't already.

I haven't reached out yet, but I will give that a shot as well.

> Right now I don't see a way forward that either doesn't involve creating inconsistencies and then either needing to fix them manually or you need to live with them until the volume in question is deleted. So, I'll reiterate that getting help from gluster may be better so that you can find out if you can either disable but not remove the bricks or get gluster to stop "overusing" the small bricks.

> if you delete the device heketi will create a bricks of same size for that volume again and attach them to the volume and you will be at the same problem again. So to get out of that problem you have to edit the heketi db, there is no other option around

The volume might live for a long time, depending on when k8s removes support for gluster and we are forced to move to something else.
Those drawbacks you both mention due to inconsistencies don't seem very attractive.

So my options are to check if the gluster devs have some good ideas that lets me keep the bricks but with less issues, or remove the bricks with gluster and edit the heketi db.

Thank you both for the input!

**Comment by phlogistonjohn** [comment] 2021-05-11 12:56
That sounds reasonable to me. As you note, heketi never checks bricks for size changes but the resync should cause heketi to see that space as "lost" and not allocate from it. I can't really comment on the gluster level behavior though.

As for the heketi db you can try living with the inconsistency, either short term or long term. If you do decide to edit the db this should mainly involve adjusting the sizes of the bricks in the db to match the new state in lvm.

**Comment by blurpy** [comment] 2021-05-12 15:46
Thanks for the input! I think gluster handles it fine at least, but what I worry a bit about is whether the resize using lvm is safe the way I did it, or if I need to change other parameters as well. I see some mention around the Internet regarding corruption if the metadata pool is too small f.ex.

**Comment by raghavendra-talur** [comment] 2021-05-12 16:52
> Thanks for the input! I think gluster handles it fine at least, but what I worry a bit about is whether the resize using lvm is safe the way I did it, or if I need to change other parameters as well. I see some mention around the Internet regarding corruption if the metadata pool is too small f.ex.

The second approach you mentioned of extending the thin pool followed by extending the brick is what we suggest.

You can remove the --resizefs option when you are extending the thinpool.

Regarding your comment about corruption if the metadata pool is too small, we have not seen that issue before. However, if you want to make changes such that the new state matches with that of heketi, here are the pointers:

1. Heketi's calculation of the metadata pool size: https://github.com/heketi/heketi/blob/69b526776a80a2651d2aa70dc6ee1a3421ba6cf8/apps/glusterfs/device_entry.go#L384
2. By my calculation, your 10GB bricks should have a .05GB of metadata size. If you want the thinpool to be 300GB like your other bricks then it should have a metadata size of 1.5GB.
3. I believe it is possible to extend the metadata size too when you are extending the pool, however I haven't tried that before.

Your plan looks good to me. The only warning for the future is that if you ever remove or evict these bricks using heketi, it will create a 10GB brick as the replacement brick and you will have to apply the same workaround there.

**Comment by blurpy** [comment] 2021-05-13 11:59
> The second approach you mentioned of extending the thin pool followed by extending the brick is what we suggest.

Excellent!

> You can remove the --resizefs option when you are extending the thinpool.

Good point.

> Regarding your comment about corruption if the metadata pool is too small, we have not seen that issue before. However, if you want to make changes such that the new state matches with that of heketi, here are the pointers:

Thank you, I will do some tests with this.

> Your plan looks good to me. The only warning for the future is that if you ever remove or evict these bricks using heketi, it will create a 10GB brick as the replacement brick and you will have to apply the same workaround there.

Yeah, have to think about whether to manually edit the heketi db to fix the inconsistencies or not.

**Comment by blurpy** [comment] 2021-05-18 08:03
To buy some time we increased the size of the pvc, and gluster started moving files away from the small bricks.
We ran into an issue though, as we already had 30 bricks, and heketi wanted 4 more, but the max is 32.

Changed the heketi config file as follows:

```
"max_bricks_per_volume" : 34
```

I see you originally had this set to 100, according to #430 and changed it to 32. What was the reason for that change? Is it troublesome to have more bricks than 32?

**Comment by raghavendra-talur** [comment] 2021-05-18 13:15
> To buy some time we increased the size of the pvc, and gluster started moving files away from the small bricks.
> We ran into an issue though, as we already had 30 bricks, and heketi wanted 4 more, but the max is 32.
> 
> Changed the heketi config file as follows:
> 
> ```
> "max_bricks_per_volume" : 34
> ```
> 
> I see you originally had this set to 100, according to #430 and changed it to 32. What was the reason for that change? Is it troublesome to have more bricks than 32?

The limit was set based on some profiling that we did with the volumes. It is very hard to come up with a number/formula which applies to different type of volume sizes and workloads. 

Considering that you have a replica 2 volume and now the brick count is set to 34, you have a DHT xlator with 17 subvols(17 different buckets for the file distribution). At some point, you might see slow listing(ls) performance of files; especially if detailed listing is requested and you can consider that as the limit. Also to remind you, as you have already discovered, heketi does not support shrinking of the volume(reducing the brick count) and in that case you will have to figure out if you want to remove the bricks from Gluster and edit Heketi db.

On the heketi side, the number of bricks don't really stress Heketi that much and it should be fine.

**Comment by blurpy** [comment] 2021-05-18 17:01
I understand. Thanks for the explanation. We still haven't decided on what to do, but this is useful to know when evaluating the options.

**Comment by phlogistonjohn** [comment] 2021-09-03 16:53
I'm triaging issues. It seems that this conversation has naturally wound down, and due to the age of the issue I'll be closing it now.

**Closed by phlogistonjohn** 2021-09-03 16:53 UTC
