### ISSUE TITLE
Cannot remove node or device

### ISSUE THREAD

**Issue by wernergillmer** [heketi/heketi#953] opened 2018-01-09 12:12 UTC
I have a failed node (vm is lost), I want to remove the node from the cluster. If I schedule a pvc in kubernetes, heketi still tries to use that node with glusterfs.

Trying to remove the node does not seem work.

    ➜  gluster (master) ✗ heketi-cli cluster list
    Clusters:
    Id:a17022931130a42a68b4e79059ac3683
    ➜  gluster (master) ✗ heketi-cli node list
    Id:43d11eedcc63827dc5a4d34888615272	Cluster:a17022931130a42a68b4e79059ac3683
    Id:629dfcd10596e3bff1994c410805bf38	Cluster:a17022931130a42a68b4e79059ac3683
    Id:74ad5b36da8ab41603eddcd3dbc0fc14	Cluster:a17022931130a42a68b4e79059ac3683
    Id:c6e04620d026a607654b380cba79a12b	Cluster:a17022931130a42a68b4e79059ac3683
    ➜  gluster (master) ✗ heketi-cli node info 43d11eedcc63827dc5a4d34888615272
    Node Id: 43d11eedcc63827dc5a4d34888615272
    State: offline
    Cluster Id: a17022931130a42a68b4e79059ac3683
    Zone: 1
    Management Hostname: 829k8pos1.local
    Storage Hostname: 10.165.210.58
    Devices:
    Id:959e5700b171477dd9252546f68c3cd1   Name:/dev/sdb            State:offline   Size (GiB):2999         Used (GiB):694     Free (GiB):2305

    ➜  gluster (master) ✗ heketi-cli node delete 43d11eedcc63827dc5a4d34888615272 force
    Error: Unable to delete node [43d11eedcc63827dc5a4d34888615272] because it contains devices

    ➜  gluster (master) ✗ heketi-cli device delete 959e5700b171477dd9252546f68c3cd1
    Error: Unable to delete device [959e5700b171477dd9252546f68c3cd1] because it contains bricks

    ➜  gluster (master) ✗ heketi-cli device disable 959e5700b171477dd9252546f68c3cd1
    Device 959e5700b171477dd9252546f68c3cd1 is now offline

    ➜  gluster (master) ✗ heketi-cli device delete 959e5700b171477dd9252546f68c3cd1
    Error: Unable to delete device [959e5700b171477dd9252546f68c3cd1] because it contains bricks
    ➜  gluster (master) ✗ heketi-cli device delete 959e5700b171477dd9252546f68c3cd1 force
    Error: Unable to delete device [959e5700b171477dd9252546f68c3cd1] because it contains bricks

**Comment by XericZephyr** [comment] 2018-03-06 21:45
Same here.

**Comment by ss75710541** [comment] 2018-03-07 08:15
I have this problem too.

**Comment by wernergillmer** [comment] 2018-03-08 08:26
This is a bit of a show stopper problem for us with Heketi / Glusterfs. It means we cannot trust heketi/glusterfs to loose a single vm out of our storage cluster, whereas all the rest of our infrastructure is build to be able to easily handle the loss of a vm.

**Comment by nelsonfassis** [comment] 2018-05-16 22:41
Same issue here, still not no updates? Isn't a way to force to delete a node from heketi? Maybe making the node offline (only thing I managed to do) might help in some cases but for me is a nightmare to keep.

**Comment by phlogistonjohn** [comment] 2018-05-17 13:18
The order of operations needed to purge a device from heketi is:
heketi-cli device disable <ID>
heketi-cli device remove <ID>
heketi-cli device delete <ID>

The first step prevents new volumes from using the device but does not touch existing volumes. The second command replaces any bricks that are located on that device with bricks on a different device. When the brick has been replaced the original brick on the target device is removed from the heketi db. Upon completion there should be no bricks on the target device and then the device can be deleted from the db.

Please note that if you are removing multiple devices (or nodes) its best to do all the disables first before running any remove commands. If you do not do this, its is possible heketi will try to put the new replacement brick on a device you plan on also removing in the near future. This could lead to unnecessary command failures or just a bunch of extra churn on the gluster nodes, depending on the state of the devices.

If you encounter unexpected errors with this procedure please feel free to report the issues to the heketi issues but please make sure you include the commands you ran, the exact output of the commands, and if possible any relevant logging. Thanks.

**Comment by noahzaozao** [comment] 2018-05-23 09:19
# heketi-cli device disable c126fdcdfaf1f9adbc42dcb900acbacd
Device c126fdcdfaf1f9adbc42dcb900acbacd is now offline

# heketi-cli device remove c126fdcdfaf1f9adbc42dcb900acbacd
Error: Get http://localhost:8080/queue/743a0a43e9526d6c3dcfaec8161e408d: dial tcp [::1]:8080: getsockopt: connection refused

**Comment by phlogistonjohn** [comment] 2018-05-23 13:22
@noahzaozao You'll need to provide more information to help us debug what happened. That's especially true since I don't know how close in time you ran these two commands. From that error message all we know is that the cli failed to connect to the server.  The cause could range from something as simple as a change in your shell's environment to a server crash.

I suggest opening a new issue for your specific problem and getting logging from the server. If you are running heketi standalone you should be able to get the logs from the journal (if using systemd) or from kubectl logs command if running under kubernetes. You should also check your environment, is heketi supposed to be running on your localhost?, is your localhost correct when it resolves to ::1 (ipv6) and/or did you configured heketi to listen on a port different from 8080, etc.

**Comment by noahzaozao** [comment] 2018-06-04 09:51
@phlogistonjohn Thanks , I think it was my mistake with config the heketi, and now I have resolved this problem.

**Comment by phlogistonjohn** [comment] 2018-09-14 15:52
Sounds like my answer helped at least one reporter of this issue. Hopefully my answer was satisfactory for the other users as well. I'm closing this issue now. If you feel the issue needs additional discussion please feel free to reopen.

**Closed by phlogistonjohn** 2018-09-14 15:52 UTC

**Comment by DineshC001** [comment] 2019-05-17 09:50
I am unable to remove remove/delete device or node either:
kubectl -n glusterfs exec -i heketi-5986d55857-jpl5k -- heketi-cli -s http://localhost:8080 --user admin --secret '' device info 864f9a5d21078b9a4cb65a9027a56a9d
Device Id: 864f9a5d21078b9a4cb65a9027a56a9d
Name: /dev/mapper/dockergroup-thinpoolstorage
**State: offline**
Size (GiB): 200
Used (GiB): 42
Free (GiB): 158
Bricks:
Id:52d862ad9f2471d4d70e9382723227bc   Size (GiB):2       Path: /var/lib/heketi/mounts/vg_864f9a5d21078b9a4cb65a9027a56a9d/brick_52d862ad9f2471d4d70e9382723227bc/brick
Id:75a3c73bcd69b3edcece26dc281924a9   Size (GiB):15      Path: /var/lib/heketi/mounts/vg_864f9a5d21078b9a4cb65a9027a56a9d/brick_75a3c73bcd69b3edcece26dc281924a9/brick
Id:9ec82ce869b0f6d2f9da2b4ac5b23696   Size (GiB):15      Path: /var/lib/heketi/mounts/vg_864f9a5d21078b9a4cb65a9027a56a9d/brick_9ec82ce869b0f6d2f9da2b4ac5b23696/brick
Id:afce8507c8a5678da91e46e4226576e4   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_864f9a5d21078b9a4cb65a9027a56a9d/brick_afce8507c8a5678da91e46e4226576e4/brick
Id:b8f9366170af504c9cf559c35bb8e9b7   Size (GiB):5       Path: /var/lib/heketi/mounts/vg_864f9a5d21078b9a4cb65a9027a56a9d/brick_b8f9366170af504c9cf559c35bb8e9b7/brick

After that I run command:

 kubectl -n glusterfs exec -i heketi-5986d55857-jpl5k -- heketi-cli -s http://localhost:8080 --user admin --secret '' device delete 864f9a5d21078b9a4cb65a9027a56a9d
Error: Unable to delete device [864f9a5d21078b9a4cb65a9027a56a9d] **because it contains bricks**

**Comment by anisha24** [comment] 2021-05-09 15:41
> The order of operations needed to purge a device from heketi is:
> heketi-cli device disable $ID
> heketi-cli device remove $ID
> heketi-cli device delete $ID
> 
> The first step prevents new volumes from using the device but does not touch existing volumes. The second command replaces any bricks that are located on that device with bricks on a different device. When the brick has been replaced the original brick on the target device is removed from the heketi db. Upon completion there should be no bricks on the target device and then the device can be deleted from the db.
> 
> Please note that if you are removing multiple devices (or nodes) its best to do all the disables first before running any remove commands. If you do not do this, its is possible heketi will try to put the new replacement brick on a device you plan on also removing in the near future. This could lead to unnecessary command failures or just a bunch of extra churn on the gluster nodes, depending on the state of the devices.
> 
> If you encounter unexpected errors with this procedure please feel free to report the issues to the heketi issues but please make sure you include the commands you ran, the exact output of the commands, and if possible any relevant logging. Thanks.

This works in almost any scenario where I would want to delete and recreate in case of failure or wrong configuration
