### ISSUE TITLE
heketi is no compatible with ubuntu16.04 lvm2

### ISSUE THREAD

**Issue by yepia** [heketi/heketi#1850] opened 2021-04-23 10:19 UTC
heketi-cli add device error,  
pvs: unrecognized option '--reportformat=json'
  Error during parsing of command line.
]

**Comment by phlogistonjohn** [comment] 2021-04-23 13:14
Sorry to hear you're having a problem, but if the issue is that ubuntu 16.04 lacks that command line switch, then ubuntu 16.04 is simply too old to use with heketi. Heketi is in maintenance only status and since this command works with many other distribution versions and is pretty fundamental to how heketi works today, we will not be making any changes to this.

I hope that makes sense & as such I will be closing this issue.

**Closed by phlogistonjohn** 2021-04-23 13:14 UTC
