### ISSUE TITLE
the readme.md in extras/kubernetes/ is  not correspond to real

### ISSUE THREAD

**Issue by 4admin2root** [heketi/heketi#748] opened 2017-04-19 15:03 UTC
for example 
there is no file named gluster-daemonset.json
and where is deploy-heketi-deployment.json

**Comment by MohamedAshiqrh** [comment] 2017-05-16 07:32
@4admin2root hey we have a [repo](https://github.com/gluster/gluster-kubernetes) which is more preferable for the kubernetes and openshift deployments as we have mentioned in the heketi [wiki](https://github.com/heketi/heketi/wiki/Kubernetes-Integration#overview).

**Comment by lpabon** [comment] 2017-06-15 03:40
Duplicate of #755

**Closed by lpabon** 2017-06-15 03:40 UTC
